tables:
  1:
    x: 62
    y: 415
    width: 1783
    height: 212
    buttons:
      blue:
        x: 164
        y: 764
      red:
        x: 345
        y: 762
      confirm:
        x: 482
        y: 749
      cancel:
        x: 604
        y: 755
    timer:
      x: 698
      y: 709
      width: 134
      height: 84
    blue_score:
      x: 678
      y: 725
      width: 52
      height: 77
    red_score:
      x: 843
      y: 704
      width: 136
      height: 87
  2:
    x: 640
    y: 0
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
  3:
    x: 1280
    y: 0
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
  4:
    x: 0
    y: 360
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
  5:
    x: 640
    y: 360
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
  6:
    x: 1280
    y: 360
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
canvas_transform_offset_x: 17
canvas_transform_offset_y: 0
