tables:
  1:
    x: 178
    y: 336
    width: 862
    height: 207
    buttons:
      blue:
        x: 749
        y: 492
      red:
        x: 963
        y: 489
      confirm:
        x: 774
        y: 534
      cancel:
        x: 0
        y: 0
    timer:
      x: 989
      y: 344
      width: 40
      height: 26
    blue_score:
      x: 295
      y: 375
      width: 44
      height: 44
    red_score:
      x: 520
      y: 381
      width: 43
      height: 36
  2:
    x: 181
    y: 557
    width: 860
    height: 201
    buttons:
      blue:
        x: 758
        y: 709
      red:
        x: 975
        y: 705
      confirm:
        x: 776
        y: 758
      cancel:
        x: 732
        y: 758
    timer:
      x: 986
      y: 560
      width: 45
      height: 30
    blue_score:
      x: 298
      y: 605
      width: 37
      height: 31
    red_score:
      x: 536
      y: 604
      width: 46
      height: 27
  3:
    x: 1280
    y: 0
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
  4:
    x: 0
    y: 360
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
  5:
    x: 640
    y: 360
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
  6:
    x: 1280
    y: 360
    width: 640
    height: 360
    buttons:
      blue:
        x: 150
        y: 280
      red:
        x: 490
        y: 280
      confirm:
        x: 320
        y: 320
      cancel:
        x: 320
        y: 350
    timer:
      x: 290
      y: 50
      width: 60
      height: 40
    blue_score:
      x: 100
      y: 100
      width: 80
      height: 40
    red_score:
      x: 460
      y: 100
      width: 80
      height: 40
canvas_transform_offset_x: 17
canvas_transform_offset_y: 0
